export default {
  users: [
    {
      id: 1,
      username: 'test1',
      password: '12345',
      email: 'test1@gmail.com',
      googleId: '',
      githubId: '',
    },
    {
      id: 2,
      username: 'test2',
      password: '12345',
      email: 'test2@gmail.com',
      googleId: '',
      githubId: '',
    },
    {
      id: 3,
      username: 'test3',
      password: '12345',
      email: 'test3@gmail.com',
      googleId: '',
      githubId: '',
    },
    {
      id: 4,
      username: 'test4',
      password: '12345',
      email: 'test4@gmail.com',
      googleId: '',
      githubId: '',
    },
    {
      id: 5,
      username: 'test5',
      password: '12345',
      email: 'test5@gmail.com',
      googleId: '',
      githubId: '',
    },
    {
      id: 6,
      username: 'test6',
      password: '12345',
      email: 'agressorios@gmail.com',
      googleId: '114847648553844843839',
      githubId: '97910780',
    },
  ],
}
