CREATE TABLE Users(
  Id INT AUTO_INCREMENT,
  Username VARCHAR(50) NOT NULL,
  Password VARCHAR(255) NOT NULL,
  Email VARCHAR(50) NOT NULL,
  GoogleId VARCHAR(255),
  GithubId VARCHAR(255),
  Created DATETIME DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (Id, Username, Email)
);