CREATE TABLE Users(
  Id INT AUTO_INCREMENT,
  Username VARCHAR(50) NOT NULL,
  Password VARCHAR(255) NOT NULL,
  Email VARCHAR(50) NOT NULL UNIQUE,
  GoogleId VARCHAR(255) UNIQUE,
  GithubId VARCHAR(255) UNIQUE,
  Created DATETIME DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (Id, Username)
);